compute_environment: LOCAL_MACHINE
debug: false
distributed_type: MULTI_GPU
enable_cpu_affinity: false
machine_rank: 0
main_training_function: main
mixed_precision: 'bf16'
num_machines: 1
num_processes: 2
rdzv_backend: static
same_network: true
use_cpu: false
